// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Medical

#ifndef _MEDICAL_UI_H
#define _MEDICAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void blood1_Animation(lv_obj_t * TargetObject, int delay);
void blood2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Medical_Screen
void ui_Medical_Screen_screen_init(void);
extern lv_obj_t * ui_Medical_Screen;
extern lv_obj_t * ui_Panel_S1;
extern lv_obj_t * ui_Label_Date;
extern lv_obj_t * ui_IMG_Wifi;
extern lv_obj_t * ui_Panel_Content;
extern lv_obj_t * ui_Slider;
extern lv_obj_t * ui_Line_1;
extern lv_obj_t * ui_Line_2;
extern lv_obj_t * ui_Line_3;
extern lv_obj_t * ui_Line_4;
extern lv_obj_t * ui_IMG_Line_1;
extern lv_obj_t * ui_IMG_Line_2;
extern lv_obj_t * ui_IMG_Line_3;
extern lv_obj_t * ui_Number_PUL;
extern lv_obj_t * ui_Label_PUL;
extern lv_obj_t * ui_Label_mmHg_3;
extern lv_obj_t * ui_Label_Sound;
extern lv_obj_t * ui_IMG_BTN_Bg;
void ui_event_BTN_Power(lv_event_t * e);
extern lv_obj_t * ui_BTN_Power;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_blood_group;
extern lv_obj_t * ui_blood1;
extern lv_obj_t * ui_blood_fill;
extern lv_obj_t * ui_blood2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_wifi_png);    // assets\wifi.png
LV_IMG_DECLARE(ui_img_img_slider_png);    // assets\img_slider.png
LV_IMG_DECLARE(ui_img_img_line_png);    // assets\img_line.png
LV_IMG_DECLARE(ui_img_img_btn_bg_png);    // assets\img_btn_bg.png
LV_IMG_DECLARE(ui_img_img_btn_off_png);    // assets\img_btn_off.png
LV_IMG_DECLARE(ui_img_img_btn_on_png);    // assets\img_btn_on.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets\wave2.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets\wave1.png

LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
