// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Medical

#include "ui.h"

void open_led(lv_event_t * e)
{
	// Your code here
}

void change_led(lv_event_t * e)
{
	// Your code here
}
