// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Medical

#include "ui.h"

void ui_Medical_Screen_screen_init(void)
{
    ui_Medical_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Medical_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Medical_Screen, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Medical_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_S1 = lv_obj_create(ui_Medical_Screen);
    lv_obj_set_width(ui_Panel_S1, lv_pct(100));
    lv_obj_set_height(ui_Panel_S1, lv_pct(100));
    lv_obj_set_align(ui_Panel_S1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_S1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_S1, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel_S1, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel_S1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel_S1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_S1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Date = lv_label_create(ui_Panel_S1);
    lv_obj_set_width(ui_Label_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Date, -5);
    lv_obj_set_y(ui_Label_Date, 13);
    lv_obj_set_align(ui_Label_Date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Date, "Infineon Gateway demo");
    lv_obj_set_style_text_color(ui_Label_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Date, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Wifi = lv_img_create(ui_Panel_S1);
    lv_img_set_src(ui_IMG_Wifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_IMG_Wifi, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_IMG_Wifi, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_x(ui_IMG_Wifi, -13);
    lv_obj_set_y(ui_IMG_Wifi, 14);
    lv_obj_set_align(ui_IMG_Wifi, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_IMG_Wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Content = lv_obj_create(ui_Panel_S1);
    lv_obj_set_height(ui_Panel_Content, 277);
    lv_obj_set_width(ui_Panel_Content, lv_pct(100));
    lv_obj_set_x(ui_Panel_Content, 0);
    lv_obj_set_y(ui_Panel_Content, 45);
    lv_obj_set_align(ui_Panel_Content, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel_Content, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Content, lv_color_hex(0xF8F8F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel_Content, lv_color_hex(0xDCE5ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel_Content, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel_Content, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Content, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider = lv_slider_create(ui_Panel_Content);
    lv_slider_set_value(ui_Slider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider, 19);
    lv_obj_set_height(ui_Slider, 194);
    lv_obj_set_x(ui_Slider, -94);
    lv_obj_set_y(ui_Slider, -22);
    lv_obj_set_align(ui_Slider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider, lv_color_hex(0xD0D7DF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Slider, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider, &ui_img_img_slider_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Line_1 = lv_obj_create(ui_Panel_Content);
    lv_obj_set_width(ui_Line_1, 10);
    lv_obj_set_height(ui_Line_1, 2);
    lv_obj_set_x(ui_Line_1, -8);
    lv_obj_set_y(ui_Line_1, 85);
    lv_obj_set_style_bg_color(ui_Line_1, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line_2 = lv_obj_create(ui_Panel_Content);
    lv_obj_set_width(ui_Line_2, 10);
    lv_obj_set_height(ui_Line_2, 2);
    lv_obj_set_x(ui_Line_2, -7);
    lv_obj_set_y(ui_Line_2, 170);
    lv_obj_set_style_bg_color(ui_Line_2, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line_3 = lv_obj_create(ui_Panel_Content);
    lv_obj_set_width(ui_Line_3, 10);
    lv_obj_set_height(ui_Line_3, 2);
    lv_obj_set_x(ui_Line_3, 28);
    lv_obj_set_y(ui_Line_3, 170);
    lv_obj_set_style_bg_color(ui_Line_3, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line_4 = lv_obj_create(ui_Panel_Content);
    lv_obj_set_width(ui_Line_4, 10);
    lv_obj_set_height(ui_Line_4, 2);
    lv_obj_set_x(ui_Line_4, 29);
    lv_obj_set_y(ui_Line_4, 85);
    lv_obj_set_style_bg_color(ui_Line_4, lv_color_hex(0x132234), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Line_1 = lv_img_create(ui_Panel_Content);
    lv_img_set_src(ui_IMG_Line_1, &ui_img_img_line_png);
    lv_obj_set_width(ui_IMG_Line_1, 224);
    lv_obj_set_height(ui_IMG_Line_1, 2);
    lv_obj_set_x(ui_IMG_Line_1, 15);
    lv_obj_set_y(ui_IMG_Line_1, 85);
    lv_obj_set_align(ui_IMG_Line_1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_IMG_Line_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Line_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Line_2 = lv_img_create(ui_Panel_Content);
    lv_img_set_src(ui_IMG_Line_2, &ui_img_img_line_png);
    lv_obj_set_width(ui_IMG_Line_2, 224);
    lv_obj_set_height(ui_IMG_Line_2, 2);
    lv_obj_set_x(ui_IMG_Line_2, 10);
    lv_obj_set_y(ui_IMG_Line_2, 171);
    lv_obj_set_align(ui_IMG_Line_2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_IMG_Line_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Line_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IMG_Line_3 = lv_img_create(ui_Panel_Content);
    lv_img_set_src(ui_IMG_Line_3, &ui_img_img_line_png);
    lv_obj_set_width(ui_IMG_Line_3, 224);
    lv_obj_set_height(ui_IMG_Line_3, 2);
    lv_obj_set_x(ui_IMG_Line_3, 10);
    lv_obj_set_y(ui_IMG_Line_3, 255);
    lv_obj_set_align(ui_IMG_Line_3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_IMG_Line_3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Line_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Number_PUL = lv_label_create(ui_Panel_Content);
    lv_obj_set_x(ui_Number_PUL, 3);
    lv_obj_set_y(ui_Number_PUL, 5);
    lv_obj_set_align(ui_Number_PUL, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Number_PUL, "100");
    lv_obj_set_style_text_color(ui_Number_PUL, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Number_PUL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Number_PUL, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_PUL = lv_label_create(ui_Panel_Content);
    lv_obj_set_width(ui_Label_PUL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_PUL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_PUL, 4);
    lv_obj_set_y(ui_Label_PUL, 18);
    lv_obj_set_align(ui_Label_PUL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label_PUL, "value");
    lv_obj_set_style_text_color(ui_Label_PUL, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_PUL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_PUL, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_mmHg_3 = lv_label_create(ui_Panel_Content);
    lv_obj_set_width(ui_Label_mmHg_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_mmHg_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_mmHg_3, 3);
    lv_obj_set_y(ui_Label_mmHg_3, 43);
    lv_obj_set_align(ui_Label_mmHg_3, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label_mmHg_3, "%");
    lv_obj_set_style_text_color(ui_Label_mmHg_3, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_mmHg_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_mmHg_3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Sound = lv_label_create(ui_Panel_Content);
    lv_obj_set_width(ui_Label_Sound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Sound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Sound, 1);
    lv_obj_set_y(ui_Label_Sound, 203);
    lv_label_set_text(ui_Label_Sound, "Slider");
    lv_obj_set_style_text_color(ui_Label_Sound, lv_color_hex(0x1D3450), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Sound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Sound, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Sound, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_BTN_Bg = lv_img_create(ui_Panel_Content);
    lv_img_set_src(ui_IMG_BTN_Bg, &ui_img_img_btn_bg_png);
    lv_obj_set_width(ui_IMG_BTN_Bg, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_BTN_Bg, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_IMG_BTN_Bg, 0);
    lv_obj_set_y(ui_IMG_BTN_Bg, 90);
    lv_obj_set_align(ui_IMG_BTN_Bg, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_IMG_BTN_Bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_BTN_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTN_Power = lv_obj_create(ui_IMG_BTN_Bg);
    lv_obj_set_width(ui_BTN_Power, 65);
    lv_obj_set_height(ui_BTN_Power, 65);
    lv_obj_set_align(ui_BTN_Power, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Power, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_BTN_Power, 102, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTN_Power, &ui_img_img_btn_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BTN_Power, &ui_img_img_btn_on_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BTN_Power, lv_color_hex(0x00A1FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BTN_Power, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BTN_Power, 30, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BTN_Power, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_BTN_Power, &ui_img_img_btn_off_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_BTN_Power, lv_color_hex(0x1690FA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_BTN_Power, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Chart = lv_chart_create(ui_Panel_Content);
    lv_obj_set_width(ui_Chart, 158);
    lv_obj_set_height(ui_Chart, 78);
    lv_obj_set_x(ui_Chart, 38);
    lv_obj_set_y(ui_Chart, 4);
    lv_obj_set_align(ui_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart, 4);
    lv_chart_set_div_line_count(ui_Chart, 5, 5);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_X, 5, 5, 0, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_PRIMARY_Y, 3, 5, 4, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 2, false, 20);
    lv_chart_series_t * ui_Chart_series_1 = lv_chart_add_series(ui_Chart, lv_color_hex(0xFE1068),
                                                                LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart_series_1_array[] = { 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_1, ui_Chart_series_1_array);
    lv_chart_series_t * ui_Chart_series_2 = lv_chart_add_series(ui_Chart, lv_color_hex(0x43FF88),
                                                                LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart_series_2_array[] = { 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_2, ui_Chart_series_2_array);
    lv_chart_series_t * ui_Chart_series_3 = lv_chart_add_series(ui_Chart, lv_color_hex(0xFCFF00),
                                                                LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart_series_3_array[] = { 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart, ui_Chart_series_3, ui_Chart_series_3_array);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0xEDECF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blood_group = lv_obj_create(ui_Panel_Content);
    lv_obj_set_width(ui_blood_group, 65);
    lv_obj_set_height(ui_blood_group, 65);
    lv_obj_set_x(ui_blood_group, -16);
    lv_obj_set_y(ui_blood_group, 89);
    lv_obj_set_align(ui_blood_group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_blood_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_blood_group, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_blood_group, lv_color_hex(0xAC5D61), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_blood_group, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_blood_group, lv_color_hex(0xDEE6EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_blood_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_blood_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_blood_group, lv_color_hex(0xDEE6EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_blood_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blood1 = lv_img_create(ui_blood_group);
    lv_img_set_src(ui_blood1, &ui_img_wave2_png);
    lv_obj_set_width(ui_blood1, 400);
    lv_obj_set_height(ui_blood1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_align(ui_blood1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blood1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blood1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blood_fill = lv_obj_create(ui_blood_group);
    lv_obj_set_width(ui_blood_fill, 70);
    lv_obj_set_height(ui_blood_fill, 32);
    lv_obj_set_x(ui_blood_fill, 0);
    lv_obj_set_y(ui_blood_fill, 13);
    lv_obj_set_align(ui_blood_fill, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_blood_fill, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blood_fill, lv_color_hex(0xDE615A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blood_fill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_blood_fill, lv_color_hex(0xDE1810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_blood_fill, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_blood_fill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blood2 = lv_img_create(ui_blood_group);
    lv_img_set_src(ui_blood2, &ui_img_wave1_png);
    lv_obj_set_width(ui_blood2, 400);
    lv_obj_set_height(ui_blood2, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_blood2, -30);
    lv_obj_set_y(ui_blood2, -2);
    lv_obj_set_align(ui_blood2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blood2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blood2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Power, ui_event_BTN_Power, LV_EVENT_ALL, NULL);

}
